services:
  - type: web
    name: stock-management-api
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://Stock_Database_owner:npg_9REjbMoDi2wc@ep-misty-mountain-a15c30qc-pooler.ap-southeast-1.aws.neon.tech/Stock_Database?sslmode=require 