# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run.py'],
    pathex=['E:\\stock_project'],
    binaries=[],
    datas=[
        ('src/app', 'app'),
        ('src/app/database/stock.db', 'app/database'),
        ('static', 'static'),
        ('C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python313\\tcl', 'tcl')
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkcalendar',
        'requests',
        'subprocess',
        'sys',
        'os',
        'tempfile',
        'json',
        'shutil',
        'datetime',
        'csv',
        'psycopg',
        'flask',
        'flask_sqlalchemy',
        'flask_migrate',
        'dotenv',
        'python-dotenv',
        'flask_cors',
        'werkzeug.security',
        'sqlalchemy.exc',
        'waitress',
        'app.api.app',
        'app.main',
        'app.ui',
        'app.database'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='run',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='run',
)
